### ISSUE TITLE
Bernard integration

### ISSUE THREAD

**Issue by henrikbjorn** [thephpleague/tactician-bernard#15]
Hey

This seems like a cool usage of Bernard, and a usecase i had myself for another CQRS like library. Having said that i have some comments about how Bernard is used here.
1. The middleware uses Queue objects directly. This is a bad idea as the Producer emit events for producing and allows for customization of messages. Instead the queue command interface could use the second argument to produce for specifying the queue name https://github.com/bernardphp/bernard/blob/master/src/Producer.php#L30.
2. Routing. The routing in Bernard is not really supposed to be reimplemented, instead i would suggest you specify in the documentation that, a LocalCommandBus should be used as the receiver, and how to register that in the default bernard router. Even more so, since you are not using composition and therefor not allowing it to fall through to other routers.

On a personal opininated note: I think it makes sense to have a LocalCommandBus (sequential) and a QueueCommandBus and in that way allow the developer the flexibility of async or sync execution.

Keep up the good work :)

**Comment by sagikazarmark** [comment]
Hey @henrikbjorn !
1. This is something that I was thinking about. The reason I didn't choose this path is that we don't really need the producer in this case. We have our own events emitted. Also, a command is a special type of message and I don't really like the idea of having the destination queue part of the command. That's an architectural detail which depends on the application not the command itself. (I am not really fan of the current producer/consumer code at all. I only removed the custom consumer code because @rosstuck asked and at the end I agreed that it should not be part of this repo, but another one (or rewritten in the core repo :stuck_out_tongue: ))
2. I am not really sure why you say that. If this is the case, why do routers exist at all? Also, in this specific case I hardly think that allowing any other logic to process commands is a good idea. Worker command buses should only handle commands and nothing else. But you are always free to use the core routers.

Note: can't agree more. I don't think using the same command bus makes any sense, but others do.

Thanks for your kind words. :)

**Comment by henrikbjorn** [comment]
@sagikazarmark 
1. The Producer/Consumer is a pattern which Bernard i modelled after. By going around the producer you are removing a core functionality of Bernard which can be used for logging, statsd collecting, proxying to other bernard instances etc. The command is special for you as a user, it is not a special message in the sense of Bernard.
2. The Router are internal Bernard concept so Bernard knows how to dispatch the incoming messages to specific Receivers by name. Here you are also limiting the usage of Bernard in an application, as you are forcing applications to only use Bernard for commands.

I would strongly suggest keeping the usage as close to described i the Bernard documentation and use the model for which Bernard was modelled.

A downside of using a direct queue is that commands can only ever be sent to the same queue and not prioritized as "high" "medium" etc. where a backup would be a "low" priority and have a single consumer where "UserRegister" would be of a higher priority.

**Comment by sagikazarmark** [comment]
1. I will put this on the todo list, will do some research. I would be glad to hear your opinion as soon as I come up with something. I can think of NamedCommand wrapper where you pass in a queue name as well. However it is hard thing, because we have to keep in mind, that the commands are passed through the command bus first (which might not even contain a queue middleware). The note on the command being special was meant to say that it is a message and messages (preferabiy) does not contain their destination.
2. The point IS to limit functionality, so that you don't pass anything to a CommandBus which it does not handle. It is useful when you only use Bernard to handle commands and nothing else. As said, you can still use the core routers if you want. (And is useful in the case described in #11, which is....meh, rather not talking about it)

I agree with you that if we say commands are messages then we should extend the logic instead of overriding it.

**Comment by henrikbjorn** [comment]
2, You cannot as Bernard only uses a single Router, in this case it can add yours and not anything else. Or use the core Router and then it would be the same. Point being you either end up with confused users, or users who have to design their whole system around commands. Imagine a legacy system that uses Bernard and not Commands, now you force your users to change their entire project instead of changing it piece by piece.

**Comment by sagikazarmark** [comment]
Noone is forcing anything. As you pointed, it is possible to register the current router logic in the core router.

**Comment by rosstuck** [comment]
Hi @henrikbjorn,

Thanks for the feedback! I really appreciate you taking the time to peek in on this. :smile: 

In regards to the points you've raised,
1. That makes a lot of sense. I haven't used Bernard in production yet but I'd prefer we continue to support all of the original plugins etc where possible. Between this and some other ongoing discussions (queuing flag), I almost wish we had some way to attach arbitrary metadata to a command ala JMS\Metadata. Barring that, if there's really this many naming/priority/queueing options, perhaps we should (re)consider some getters on an interface/trait combo, @sagikazarmark? :unamused: Something for our other ongoing discussion perhaps.
2. Technically, there could be a composite Router which would allow partial migration. I do feel the current Router interface is a valuable add-on point and unless there's some pending rework there that'll trip us up, I hope you'll consider making a supported interface. Tactician is really just a fancy-pants lightweight router in the generic sense so this this seems like an ideal add-on point. If you're unsure about these usecases, what about extending it to support a Chain of Responsibility? (in terms of something like Chainlink https://github.com/Symbid/chainlink ) That could be done in a way that doesn't break BC, I think.
3. Regarding separate local vs remote command buses, I'm in the "other" camp and would prefer a single entry point to the service/application layer which then makes the choice between sync and async (just like a remote HTTP server would), rather than leaving it as something that's (roughly-speaking) on the client's end. I know not everyone agrees with that opinion and there are some possible exceptions (debug tools, for example) but the current setup does allow someone to build it out either way. :)

Thanks again for your input! If you've got any other thoughts on points 1 & 2, or anything else related to Tactician in general, please let us know!

Many thanks,
-Ross

**Comment by henrikbjorn** [comment]
Hey @rosstuck 

I'll start with the Router as my mind is already kind of set of converting you guys :) And the others need a bit more thought.

The Routers inception was because we wanted to be able to lazy load Receivers and their dependencies. That way you wouldnt have to connect to the database when setting up the receivers, also you could easily map them by name -> serviceId. Pairing this with the BernardBundle and its tag you can automatically register a receiver in another bundle. This would make it extremely easy for users for both BernardBundle and TacticianBundle to setup.

Other users would have a bit more setup to do, but nothing more than the following (assuming you are using silex, which we are at work)

``` php
// $app = Silex\Applicaction configured with bernard and tactician
$app['bernard.receivers'] = [
    'TacticianCommand' => ['tactician.command_bus', 'handle'],
];
```

For a pure php application

``` php
$router->add('TacticianCommand', [$commandBus, 'handle']);
```

This way it becomes a purely documentation issue, an issue you would have aswell. Because you would have to explain why to change the Router already setup when using Bernard etc.

Composition could be a saviour, but on a personally i dont think there is a need to implement something for the sake of implementing it :)

**Comment by henrikbjorn** [comment]
Priority/QueueNaming

By default Bernard tries to guess the name for the queue based on the Message object given (is getName returns the class name). So `ImportantMessage` would be sent to `important` queue. So using a prioritation system is a matter of the name of the message.

Serialization is HARD! Which Bernard learned the hard way. The master branch of Bernard uses a Normalizier instead and have a single serializer that supports json. This way the format is an internal concern for bernard and the only thing the end users need to understand, is converting their object graph into an array and back (basically). It should be possible to create a Normalizer for Commands as long as Commands would not contains complex types.

**Comment by henrikbjorn** [comment]
Sync/Async Busses.

I dont really have a say in this. But imagine you have one command "ImportCommand" which you would like to be force run locally because you are doing it in a cron script (yeah bad idea, but you get the point) and other times you want it to just run and not wait for it.

**Comment by sagikazarmark** [comment]
My personal problem with "guessing the queue from the message" is that we are limiting ourselves with it. We have to follow a naming convention in order to send messages to the specific queue.

**Comment by henrikbjorn** [comment]
The Queue guessing is deterministic, so if your Message returns `TacticianCommand` from `getName()` then tactician-command would be used.

**Comment by henrikbjorn** [comment]
Also, the produce method takes a second argument to chose which queue should be used, if that is set the guessing is not done.

**Comment by sagikazarmark** [comment]
Yeah, but in this case there is no way to pass a second argument runtime. Either stick to one queue, or rely on the naming.

**Comment by henrikbjorn** [comment]
@sagikazarmark That is the way that Bernard was designed to work, the Message getName() overrides the name and eliminates the guessing.

Also the Queue concept as it is currently is going to change, in order to have a model that feels closer to RabbitMQ with Exchanges etc.

**Comment by sagikazarmark** [comment]
Thinking about the Router thing: we are currently trying to make it work with a single command bus. If we use the core router we cannot return a custom callable which wraps the message into a special Command. However I am willing the sacrifice the single command bus goal if we say we are trying to strictly follow bernard logic.

About the producer thing: you are probably right about it. To tell the truth I am currently using this package in a simple application, but in case of a more complex app, it might not be enough to send messages to one queue.

**Comment by henrikbjorn** [comment]
Regarding the Router. SInce you control the receiver, you can have the receiver do the special wrapping before it is getting handled by the command bus.

``` php

class CommandReciever {
     public function __construct($commandBus) {
         $this->commandBus = $commandBus;
     }

     public function tacticianCommand(Message $message)
     {
         $this->commandBus->handle(new QueuedCommand($message));
     }
}
```

Or something like it, the only difference is that you are opening up for flexibility and moving the logic somewhere else :)

**Comment by sagikazarmark** [comment]
@henrikbjorn #17 and #18 addressed all the issues you mentioned. Any ideas?

**Comment by henrikbjorn** [comment]
Looks good :)

Only thing i saw was something about making commands mutable, commands cannot be mutable according to the way the design pattern is specified.

**Comment by sagikazarmark** [comment]
That's something we are struggling with. Currently we are solving things by
command wrapping.

**Comment by sagikazarmark** [comment]
I think this is done
