### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician-bernard#20]
@rosstuck I am ready to tag v0.2

**Comment by rosstuck** [comment]
Last thing and I'll shut up: maybe consider moving the abstract Receiver to the Receiver directory. Otherwise, no blockers here.

**Comment by sagikazarmark** [comment]
I prefer objects (classes, interfaces) not moving in folders named after them. The reason is that the topmost object declares the type and everything belongs under that namespace.

Think about it as word repetition: you have an interface Car and a class Ford. Ford is a Car, but Car is not a Car, thus you don't place Car in Cars. And we know that word repetition is bad. :)

I think this is cleaner logic than moving under a folder for the sake of grouping the same named things.

**Comment by rosstuck** [comment]
I've heard this called (somewhat indelicately) "the namespace sutter". I would offer an alternate interpretation: that a namespace is a topic under which multiple items can be grouped. I.e. when you talk about Cars you often talk about Drivers, Passengers, Roads and Cars. Just because the topic Cars contains the actual thing "Cars" doesn't mean they're bad. I'm too tired to go further on this one though, tag if you like. :)

**Comment by sagikazarmark** [comment]
I can see potential in both logic. There are some cases when a "topic" is so big, that you collect several things under it. But I usually try to keep it as simple as and as small as possible.
