### ISSUE TITLE
PHP7 failure

### ISSUE THREAD

**Issue by rosstuck** [thephpleague/tactician-bernard#25]
Not pressing, but seems like with the latest release there was a test failure only on PHP7. Haven't had a chance to check it out yet.

**Comment by rosstuck** [comment]
https://travis-ci.org/thephpleague/tactician-bernard/jobs/61768404

**Comment by sagikazarmark** [comment]
PHP 7 does not work with PHPSpec ATM. The problem is that the recoverable errors have been removed from PHP 7 which is used to hack the type hinting system.

See the issue I reported: phpspec/phpspec#659

So PHP 7 failure is allowed with a cause. If it won't get solved by the time PHP 7 is released, I will rewrite the tests to use annotations for mocking, but that is not as nice as the type hinting one IMO.

**Comment by ciaranmcnulty** [comment]
I aim to have this fixed before PHP7 is stable.

**Comment by sagikazarmark** [comment]
:+1: Awesome

**Comment by ciaranmcnulty** [comment]
(so 5.x codebases will run on the PHP7 engine but we might not support new PHP7 features)

**Comment by sagikazarmark** [comment]
For now, I think it is acceptable.

**Comment by frankdejonge** [comment]
@rosstuck I think this can be closed now.

**Comment by ciaranmcnulty** [comment]
The 'before PHP7 is stable' now may mean 'dev-master works' ;-P

**Comment by rosstuck** [comment]
Going to hold off until there's a stable PHPSpec release that we depend on in our composer. Then I know it's totally done. :)

**Comment by ciaranmcnulty** [comment]
`2.4.0-alpha1` is out now and as far as I can see your tag `0.4.1` passes with this version so it'll likely be fine with the stable release when it comes.

**Comment by sagikazarmark** [comment]
Thanks for letting us know.

**Comment by sagikazarmark** [comment]
Done
